### PR TITLE
Added Compression, nice error rendering 

### PR DESCRIPTION
**Pull request by bytedeveloperr**

### CODE REVIEW

**Comment by EphraimDev** [comment]
You have merge conflicts 

Why is this ejs necessary? Is this to print the error to the console?

**Comment by papa28x4** [comment]
@EphraimDev ejs is a templating engine for rendering dynamic content to the client.

**Comment by EphraimDev** [comment]
@papa28x4 your api should be sending json back to the client. I know what ejs is, I'm just wondering why it's useful here

**Comment by papa28x4** [comment]
Oh I get.. In this case there's no need for it.

**Comment by EphraimDev** [comment]
No response on this after 24 hours

**Pull request closed without merging**
